# Generated by Django 4.2.4 on 2023-12-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_article_published_on_alter_review_published_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(related_name='articles_authors', to='main_app.author'),
        ),
    ]
