# Generated by Django 4.2.4 on 2023-10-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_department_location_alter_employee_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='last_edited_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
